version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    hostname: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    command: >
      bash -c "npm install
      && npm run start"
    depends_on: 
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
  
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    hostname: nginx
    networks: 
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - db
      - app
      
networks: 
  node-network:
    driver: bridge     
